services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  flyway:
    image: flyway/flyway
    depends_on:
      - db
    entrypoint: [ "flyway", "migrate" ]
    env_file:
      - .env
    environment:
      - FLYWAY_URL=${FLYWAY_URL}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/sql:/flyway/sql
      - ./db/flyway.conf:/flyway/conf/flyway.conf
    networks:
      - app_network
  api:
    build:
      context: ./backend
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ~/.aws/:/root/.aws:ro
    environment:
      - AWS_PROFILE=default
    depends_on:
      - db
    networks:
      - app_network
  app:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/src
      - node_modules:/app/node_modules
    depends_on:
      - api
    networks:
      - app_network


volumes:
  postgres_data:
  node_modules: {}

networks:
  app_network:
    driver: bridge

